# Generated by Django 5.2.8 on 2025-11-15 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='webhook',
            name='last_response_time_ms',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='webhook',
            name='event_type',
            field=models.CharField(choices=[('import.completed', 'Import completed')], default='import.completed', max_length=64),
        ),
    ]
