# Generated by Django 5.2.8 on 2025-11-15 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_webhook_last_response_time_ms_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='webhook',
            name='name',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
    ]
